
import DashboardNav from '../../src/components/Common/DashboardNav'


export default function DashboardHome() {
  return (
    <div>
      <head>
       <title>Responsive Sidebar Menu</title>
       <meta name="description"  content="generated by create next app "/>
       <link rel="icon" href="/pro.ico"/>
       
      </head>
    {/* <DashboardNav/> */}
    </div>
  )
}