import { NextPage } from "next";
import DashboardNav from "../../src/components/Common/DashboardNav";
import Head from "next/head";

export default function DashboardHome() {
  return (
    <div>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="generated by create next app " />
        <link rel="icon" href="/pro.ico" />
      </Head>
      {/* <DashboardNav/> */}
    </div>
  );
}
